# Generated by Django 5.2.4 on 2025-07-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chatmessage_chatsession_vehicle_delete_onboarduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='annual_mileage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='commute_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='commute_miles',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='use_type',
            field=models.CharField(max_length=50),
        ),
    ]
