# Generated by Django 5.2.4 on 2025-07-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_vehicle_annual_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='blind_spot',
            field=models.CharField(max_length=20),
        ),
    ]
