# Generated by Django 5.2.4 on 2025-07-28 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_alter_vehicle_blind_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('vehicle_count', models.IntegerField(blank=True, null=True)),
                ('license_type', models.CharField(max_length=20, null=True)),
                ('license_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='license_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='zip_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.user'),
        ),
    ]
