# Generated by Django 5.2.4 on 2025-07-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_user_alter_chatsession_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['zip_code']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['vin']},
        ),
    ]
